## Dedicated KSB & Competency Mapping Table

| Competency & Knowledge Area | Assessment Standard Requirement | Practical Implementation (Exercise 1) | Distinction Evidence & Alignment |
| :--- | :--- | :--- | :--- |
| **TC2 & TK2: Network Engineering**[cite: 2] | Design, build, configure, optimize, test, and troubleshoot complex multi-subnet networks[cite: 2]. | Build 3-subnet Packet Tracer topology (Management, DMZ, Internal) with OSPF routing and subinterfaces[cite: 2]. | Compare Layer 3 Router vs. Core Switch topologies; log complex OSPF troubleshooting resolution[cite: 2]. |
| **TC4 & TK4: Digital System Building**[cite: 2] | Build, test, and debug a digital system to specification employing multiple components[cite: 2]. | Deploy a Linux OS VM in Hyper-V integrated with web application services and local network controls[cite: 2]. | Validate end-to-end telemetry and inter-component communication between client, network gateway, and VM[cite: 2]. |
| **TC5 & TK5: OS Hardening & Security**[cite: 2] | Configure OS in accordance with security policy, identify threats, and apply security features[cite: 2]. | Enforce SSH key-based login, lock root access, configure `pam_pwquality`, deploy UFW firewall, and Fail2ban[cite: 2]. | Document residual OS vulnerability risks and map kernel/system hardening policies to organizational policy[cite: 2]. |
| **TC8: Software Interfacing & Exploit Analysis**[cite: 2] | Construct software interacting with the real world; analyze for buffer overflows, brute force, or SQLi[cite: 2]. | Build a Python Flask web app handling authenticated file uploads, file management, and per-user directory isolation[cite: 2]. | Execute and capture proof of blocked file upload attacks (`.php` whitelist block) and path traversal (`../` sanitization)[cite: 2]. |
| **TC18 & TK18: Security Components & Crypto**[cite: 2] | Configure $\ge 2$ security components, design crypto system, and implement key management[cite: 2]. | Deploy dual-layer firewalls (ACLs + UFW), Fail2ban, TLS 1.3 transport security, and AES-256 file encryption[cite: 2]. | Document a full Key Management Lifecycle (generation, secure storage, 90-day rotation, and revocation)[cite: 2]. |
| **TC19 & TK19: Security Case Design**[cite: 2] | Design and evaluate a system in accordance with a justified security case[cite: 2]. | Develop a Claim-Argument-Evidence (CAE) matrix covering system threats and implemented mitigations[cite: 2]. | Encompass all 3 layers: Enterprise (Policy/IAM), Network (VLANs/TLS), and Application (Validation/AES-256)[cite: 2]. |
| **TC20 & TK20: Secure Architecture & Assurance**[cite: 2] | Architect, analyze, and justify a secure system to achieve security assurance[cite: 2]. | Map implemented security controls to legal mandates, business risk appetite, and threat profiles[cite: 2]. | Relate all architectural measures to NIST SP 800-53 Rev. 5 and NCSC CAF principles for formal risk owner confidence[cite: 2]. |
| **TC26 & TK26: InfoSec Policy & Legislation**[cite: 2] | Apply information security policy implementing legal and regulatory requirements[cite: 2]. | Draft an InfoSec policy governing file storage, user credentials, and acceptable system usage[cite: 2]. | Align controls with UK GDPR / DPA 2018, Computer Misuse Act 1990, and an international standard (e.g., EU NIS 2)[cite: 2]. |

---
